%% Meta-analysis figures: batch version
% This script runs every supported empirical example in one invocation.
% There is no case selector to edit manually.
% The cases are evaluated in this order:
%
%    2   - Doi et al. example (manuscript Figure 5)
%    8   - two-study conflicting-evidence example (Figure 3)
%    8.1 - Section 4.2 example and interval progression (Figure 4)
%    12  - Menkveld et al. (2024), H1 Stage 3 (Figure 6)
%
% Each iteration returns a structure in case_results and its main figure
% handle in figure_handles. Case 8.1 also creates an interval-progression
% figure, whose handle is collected in additional_figure_handles and stored
% with its calculations in case_results. Case-specific calculations are
% stored in nested fields, so later cases do not overwrite earlier results.
%
% Reproduction scope:
%   - This file generates manuscript Figures 3-6, collects the calculations
%     for manuscript Table 1, and prints that table in the Command Window.
%   - Figures 1-2 are generated by Simple_figure_v3_github.m.
%   - The case-12 result is the H1 Stage-3 illustration. Quantiles for all
%     hypotheses and stages are retained in metadata, but this script does
%     not regenerate every entry in manuscript Table 2.
%
% Figure sizes are fixed in pixels. They were calibrated against the source
% figures in the revised Statistica Neerlandica manuscript. Fixed sizes
% avoid changes caused by monitor resolution.

close all;
clearvars;

%% Batch configuration
my_q = norminv(0.975);                 % Standard-normal 97.5% quantile.
case_ids = [2, 8, 8.1, 12];           % Run every supported case in order.

% Set the figures you want to export to true. The five positions correspond
% to: case 2, case 8, case 8.1, case 8.1 prediction by n, and case 12.
% These indicators affect PDF export only; all figures are still computed.
print_figures = [false, false, false, false, false];

% Use a predictable, cross-platform output folder when PDF export is on.
script_directory = fileparts(mfilename('fullpath'));
output_directory = fullfile(script_directory, 'output', 'pdf');
if any(print_figures) && ~isfolder(output_directory)
    mkdir(output_directory); %#ok<UNRCH>
end

% The arrays below remain available in the workspace after the script ends.
case_results = struct([]);
figure_handles = gobjects(numel(case_ids), 1);
additional_figure_handles = gobjects(0, 1);

%% Run every case
for case_index = 1:numel(case_ids)
    current_case = case_ids(case_index);
    fprintf('Running meta-analysis case %g ...\n', current_case);

    [current_result, figure_handles(case_index)] = ...
        run_meta_analysis_case(current_case, my_q, ...
                               print_figures, output_directory);

    % Initialize the structure array from the first completed case. Later
    % cases have the same top-level fields and can be appended directly.
    if case_index == 1
        case_results = current_result;
    else
        case_results(case_index) = current_result;
    end

    % Most cases have one figure. Keep any case-specific supplementary
    % figures in a separate array without changing figure_handles.
    if ~isempty(current_result.additional_figure_handle)
        additional_figure_handles(end+1, 1) = ...
            current_result.additional_figure_handle;
    end
end

fprintf('Completed %d meta-analysis cases and created %d figures.\n', ...
        numel(case_ids), numel(figure_handles)+numel(additional_figure_handles));

%% Verify the reference calculations
verify_reference_results(case_results);
fprintf('All numerical verification checks passed.\n');

%% Collect and print manuscript Table 1
% Keep the unrounded results in the workspace and print the three-decimal
% presentation used in the revised manuscript.
table1_results = collect_table1_results(case_results);
print_table1_results(table1_results, result_for_case(case_results, 2).k);

%% Run and plot one case
function [result, figure_handle] = run_meta_analysis_case( ...
        my_case, my_q, print_figures, output_directory)
%RUN_META_ANALYSIS_CASE Compute one complete case and produce its figure.
%
% Keeping one case inside a function gives every iteration a clean local
% workspace. This is important because cases 2 and 12 create several extra
% model estimates that are not required by cases 8 and 8.1.

    is_conflicting_case = my_case == 8 || my_case == 8.1;
    data = load_case_data(my_case, my_q);

    Y_i = data.Y_i;
    sigma_i = data.sigma_i;
    LB_i = data.LB_i;
    k = length(Y_i);

    sigma2_i = sigma_i.^2;
    w_i = 1./sigma2_i;

    %% Common estimators
    % Fixed-effect estimator from Borenstein et al. (2009).
    M_FE = w_i'*Y_i / sum(w_i);
    V_FE = 1 / sum(w_i);

    % Method-of-moments random-effects estimator.
    df = k - 1;
    C = sum(w_i) - w_i'*w_i / sum(w_i);
    Q = w_i'*(Y_i.^2) - ((w_i'*Y_i)^2) / sum(w_i);
    T2 = (Q - df) / C;

    w_i_star = 1./(sigma2_i + T2);
    M_RE = w_i_star'*Y_i / sum(w_i_star);
    V_RE = 1 / sum(w_i_star);
    CI_RE = [M_RE - my_q*sqrt(V_RE); M_RE + my_q*sqrt(V_RE)];

    % OLS estimator used for the RE row in the conflicting-evidence cases.
    M_OLS = mean(Y_i);
    sigma2_eps_OLS = mean((Y_i - M_OLS).^2);
    CI_OLS = [M_OLS - my_q*sqrt(sigma2_eps_OLS/k); ...
              M_OLS + my_q*sqrt(sigma2_eps_OLS/k)];

    %% Base-case maximum-likelihood estimator
    V = diag(sigma2_i);
    X = ones(k, 1);

    if my_case == 8.1
        % Section 4.2 gives a closed-form ML solution for equal reported
        % variances. Use that expression directly so the program mirrors the
        % combined-estimate and variance equations in the manuscript rather
        % than relying on numerical optimization.
        concordant_estimate = Y_i(1);
        conflicting_estimate = Y_i(end);
        within_variance = sigma2_i(1);
        M_ML = concordant_estimate + ...
               (conflicting_estimate-concordant_estimate)/k;
        sigma2_total_ML = max(within_variance, (k-1)/k^2 * ...
                              (conflicting_estimate-concordant_estimate)^2);
        tau2_ML = sigma2_total_ML - within_variance;
    else
        % For the remaining cases, a grid search supplies a stable initial
        % value for numerical maximization of the likelihood.
        tau2_set = (0.0:0.0001:3)';
        phi_set = zeros(size(tau2_set));
        for j = 1:length(tau2_set)
            phi_set(j) = phi_tau(Y_i, X, V, tau2_set(j));
        end
        [~, grid_index] = max(phi_set);
        tau2_ML_grid = tau2_set(grid_index);

        fun = @(tau2)-phi_tau(Y_i, X, V, tau2);
        [tau2_ML, ~] = fminunc(fun, tau2_ML_grid);

        % Enforce a nonnegative between-study variance if the unconstrained
        % optimizer crosses the parameter boundary.
        if tau2_ML < 0
            A = [];
            b = [];
            Aeq = [];
            beq = [];
            lb = 0;
            ub = Inf;
            [tau2_ML, ~] = fmincon(fun, tau2_ML_grid, ...
                                   A, b, Aeq, beq, lb, ub);
        end

        M_ML = inv(X' * inv(Omega(V,tau2_ML)) * X) * ...
               (X' * inv(Omega(V,tau2_ML)) * Y_i);
    end

    %% Initialize a result record shared by every case
    % The same top-level fields are returned for all cases. Empty nested
    % structures indicate that a model does not apply to a particular case.
    result = struct( ...
        'case_id', my_case, ...
        'title', data.title, ...
        'Y_i', Y_i, ...
        'sigma_i', sigma_i, ...
        'k', k, ...
        'M_FE', M_FE, ...
        'V_FE', V_FE, ...
        'M_RE', M_RE, ...
        'V_RE', V_RE, ...
        'CI_RE', CI_RE, ...
        'M_OLS', M_OLS, ...
        'CI_OLS', CI_OLS, ...
        'tau2_ML', tau2_ML, ...
        'M_ML', M_ML, ...
        'base', struct(), ...
        'concordant_only', struct(), ...
        'n_progression', struct(), ...
        'relative', struct(), ...
        'correlated', struct(), ...
        'alternative', struct(), ...
        'NSE', struct(), ...
        'metadata', data.metadata, ...
        'figure_handle', [], ...
        'additional_figure_handle', gobjects(0, 1));

    %% Create a fixed-size figure canvas
    [figure_position, x_text, y_text_delta, paper_orientation] = ...
        figure_layout(my_case, LB_i);

    figure_handle = figure( ...
        'Units', 'pixels', ...
        'PaperPositionMode', 'auto', ...
        'Position', figure_position, ...
        'PaperOrientation', paper_orientation, ...
        'Name', sprintf('Meta-analysis case %g', my_case), ...
        'NumberTitle', 'off');
    hold on;

    if my_case == 12
        box on;
    end

    %% Plot the study-level estimates
    if my_case == 2 || is_conflicting_case
        % Cases 2, 8, and 8.1 use consecutive rows from k down to 1.
        plot(Y_i, (k:-1:1)', 'bs');
        for i = 1:k
            y_position = k - i + 1;
            plot([Y_i(i)-my_q*sigma_i(i); Y_i(i)+my_q*sigma_i(i)], ...
                 y_position*[1;1], 'b-');
            text(x_text, y_position, num2str(i));
        end
    else
        % Case 12 keeps each retained team on its original row. Gaps in the
        % plot therefore identify observations removed by the data filter.
        k_case2 = data.metadata.k_case2;
        my_points = data.metadata.my_points;
        for i = 1:k
            y_position = k_case2 - my_points(i) + 1;
            plot(Y_i(i), y_position', 'bs');
            plot([Y_i(i)-my_q*sigma_i(i); Y_i(i)+my_q*sigma_i(i)], ...
                 y_position*[1;1], 'b-');
        end
    end

    %% Plot the main model summaries
    if is_conflicting_case
        % Fixed-effect row.
        plot(M_FE, -1, 'rd');
        plot([M_FE-my_q*sqrt(V_FE); M_FE+my_q*sqrt(V_FE)], ...
             (-1)*[1;1], 'r-');
        text(x_text, -1, 'FE');

        if my_case == 8
            % Preserve Figure 3 exactly: OLS/RE confidence interval followed
            % by the method-of-moments prediction interval.
            plot(M_OLS, -2, 'rd');
            plot(CI_OLS, (-2)*[1;1], 'r-');
            text(x_text, -2, 'RE');

            plot(M_RE, -3, 'rd');
            plot([M_RE-my_q*sqrt(V_RE); M_RE+my_q*sqrt(V_RE)], ...
                 (-3)*[1;1], 'r-');
            text(x_text, -3+y_text_delta, 'prediction');
        else
            % Section 4.2 reports ML intervals for the ten-study example.
            % The total variance is 1 + tau^2. Dividing it by n gives the
            % variance of the combined estimate; without that division it
            % gives the variance used to predict a new input.
            V_ML_y = within_variance + tau2_ML;
            V_ML = V_ML_y/k;
            interval95_mean = M_ML + [-1, 1]*my_q*sqrt(V_ML);
            interval95_y = M_ML + [-1, 1]*my_q*sqrt(V_ML_y);

            plot(M_ML, -2, 'rd');
            plot(interval95_mean, (-2)*[1;1], 'r-');
            text(x_text, -2, 'RE');

            plot(M_ML, -3, 'rd');
            plot(interval95_y, (-3)*[1;1], 'r-');
            text(x_text, -3+y_text_delta, 'prediction');

            result.base = struct( ...
                'sigma2_between', tau2_ML, ...
                'sigma2_total', V_ML_y, ...
                'V_y', V_ML_y, ...
                'V_mean', V_ML, ...
                'interval95_y', interval95_y, ...
                'interval95_mean', interval95_mean);

            % The manuscript also reports the sensitivity calculation that
            % omits the conflicting final input. Derive this calculation
            % from Y_i so changes to case 8.1 propagate consistently.
            n_concordant = k - 1;
            concordant_interval95 = concordant_estimate + ...
                [-1, 1]*my_q*sqrt(within_variance/n_concordant);
            result.concordant_only = struct( ...
                'n', n_concordant, ...
                'M_FE', concordant_estimate, ...
                'V_FE', within_variance/n_concordant, ...
                'interval95_mean', concordant_interval95);
        end
    else
        % Cases 2 and 12 display the paper's base-case ML interval.
        position = -1;
        V_ML_y = tau2_ML + trace(V)/k;
        st_err_ML = sqrt(V_ML_y);
        V_ML = inv(X' * inv(Omega(V,tau2_ML)) * X);
        st_err_M_ML = sqrt(V_ML);

        plot(M_ML, position, 'rd');
        plot([M_ML-my_q*st_err_ML; M_ML+my_q*st_err_ML], ...
             position*[1;1], 'r-');
        plot([M_ML-my_q*st_err_M_ML; M_ML+my_q*st_err_M_ML], ...
             position*[1;1], 'k|');
        text(x_text, position+y_text_delta, 'Base case');

        my_q_50p = norminv(0.75);
        result.base = struct( ...
            'V_y', V_ML_y, ...
            'V_mean', V_ML, ...
            'interval95_y', [M_ML-my_q*st_err_ML, ...
                             M_ML+my_q*st_err_ML], ...
            'interval95_mean', [M_ML-my_q*st_err_M_ML, ...
                                M_ML+my_q*st_err_M_ML], ...
            'interval50_y', [M_ML-my_q_50p*st_err_ML, ...
                             M_ML+my_q_50p*st_err_ML], ...
            'interval50_mean', [M_ML-my_q_50p*st_err_M_ML, ...
                                M_ML+my_q_50p*st_err_M_ML]);
    end

    % Dotted reference line through the base-case ML estimate.
    if my_case == 12
        plot(M_ML*[1 1], [-6 data.metadata.k_case2+0.5], ':k');
    else
        plot(M_ML*[1 1], [-6 k+0.5], ':k');
    end

    % Case-specific vertical limits reproduce the submitted layouts.
    if my_case == 8
        % Leave clear space above observation 1 for the northeast legend.
        ylim([-3.5 k+2.5]);
    elseif my_case == 8.1
        ylim([-3.5 k+0.5]);
    elseif my_case == 2
        % Leave clear space above observation 1 for the northeast legend.
        ylim([-4 k+2.5]);
    else
        ylim([-10 data.metadata.k_case2+2]);
    end
    yticklabels({});

    % Figures 3, 5, and 6 use the same key in the northeast corner, with the
    % two entries stacked vertically.
    if ismember(my_case, [2, 8, 12])
        observation_legend_handle = plot(nan, nan, 'bs-');
        combined_legend_handle = plot(nan, nan, 'rd-');
        summary_legend = legend( ...
            [observation_legend_handle, combined_legend_handle], ...
            {'Observation and 95% CI', ...
             'Combined estimate and 95% interval'}, ...
            'Location', 'northeast', ...
            'Orientation', 'vertical', ...
            'NumColumns', 1, ...
            'AutoUpdate', 'off');
    end

    %% Relative-precision model for cases 2 and 12
    if ~is_conflicting_case
        % Estimate tau^2 and a common multiplier on the reported sampling
        % variances. Log parameters keep both variance terms positive.
        fun3 = @(x)-phi_tau(Y_i, X, exp(x(2))*V, exp(x(1)));
        if my_case == 2
            x0 = [log(tau2_ML), 0];
        else
            x0 = [log(0.01), 0];
        end
        [x_ML3, ~] = fminunc(fun3, x0);

        tau2_ML3 = exp(x_ML3(1));
        sigma2_eps = exp(x_ML3(2));
        M_ML3 = inv(X' * inv(Omega(sigma2_eps*V,tau2_ML3)) * X) * ...
                (X' * inv(Omega(sigma2_eps*V,tau2_ML3)) * Y_i);
        V_ML3_y = tau2_ML3 + trace(sigma2_eps*V)/k;
        st_err_ML3 = sqrt(V_ML3_y);
        V_ML3 = inv(X' * inv(Omega(sigma2_eps*V,tau2_ML3)) * X);
        st_err_M_ML3 = sqrt(V_ML3);

        result.relative = struct( ...
            'M', M_ML3, ...
            'tau2', tau2_ML3, ...
            'sigma2_multiplier', sigma2_eps, ...
            'V_y', V_ML3_y, ...
            'V_mean', V_ML3, ...
            'interval_y', [M_ML3-my_q*st_err_ML3, ...
                           M_ML3+my_q*st_err_ML3], ...
            'interval_mean', [M_ML3-my_q*st_err_M_ML3, ...
                              M_ML3+my_q*st_err_M_ML3]);

        % The submitted Doi figure displays this row; case 12 only stores
        % the numerical estimates.
        if my_case == 2
            position = -2;
            plot(M_ML3, position, 'rd');
            plot(result.relative.interval_y', position*[1;1], 'r-');
            plot(result.relative.interval_mean', position*[1;1], 'k|');
            text(x_text, position+y_text_delta, 'Relative case');
        end
    end

    %% Case-12 nonstandard-error comparison
    if my_case == 12
        % Use full-sample quartiles, matching the submitted analysis, and
        % stretch the interquartile range to a normal 95% interval.
        Y_i_original = data.metadata.Y_i_original;
        summary_stats = prctile(Y_i_original, [25 50 75]);
        q3 = norminv(0.75);
        NSE_interval = [ ...
            summary_stats(2) + ...
                (summary_stats(1)-summary_stats(2))*my_q/q3; ...
            summary_stats(2) + ...
                (summary_stats(3)-summary_stats(2))*my_q/q3];

        position = -8;
        plot(summary_stats(2), position, 'rd');
        plot(NSE_interval, position*[1;1], 'r-');
        text(x_text, position+y_text_delta, 'NSE interval (adjusted)');

        result.NSE = struct( ...
            'quartiles', summary_stats, ...
            'adjusted_interval95', NSE_interval', ...
            'exact_percentiles', prctile(Y_i_original, ...
                [0 10 25 50 75 90 100], "Method", "exact"));
    end

    %% Correlated extensions used only for case 2
    if my_case == 2
        % Autocorrelation in the reported sampling-error covariance.
        fun4 = @(x)-phi_tau(Y_i, X, V_ac(V,x(2)), x(1));
        x0 = [tau2_ML, 0.9];
        A = [];
        b = [];
        Aeq = [];
        beq = [];
        lb = [0, -1];
        ub = [Inf, 1];
        [x_ML4, ~] = fmincon(fun4, x0, A, b, Aeq, beq, lb, ub);

        tau2_ML4 = x_ML4(1);
        rho_ML4 = x_ML4(2);
        M_ML4 = inv(X' * inv(Omega(V_ac(V,rho_ML4),tau2_ML4)) * X) * ...
                (X' * inv(Omega(V_ac(V,rho_ML4),tau2_ML4)) * Y_i);
        V_ML4_y = tau2_ML4 + trace(V)/k;
        st_err_ML4 = sqrt(V_ML4_y);
        V_ML4 = inv(X' * inv(Omega(V_ac(V,rho_ML4),tau2_ML4)) * X);
        st_err_M_ML4 = sqrt(V_ML4);

        result.correlated = struct( ...
            'M', M_ML4, ...
            'tau2', tau2_ML4, ...
            'rho', rho_ML4, ...
            'V_y', V_ML4_y, ...
            'V_mean', V_ML4, ...
            'interval_y', [M_ML4-my_q*st_err_ML4, ...
                           M_ML4+my_q*st_err_ML4], ...
            'interval_mean', [M_ML4-my_q*st_err_M_ML4, ...
                              M_ML4+my_q*st_err_M_ML4]);

        position = -3;
        plot(M_ML4, position, 'rd');
        plot(result.correlated.interval_y', position*[1;1], 'r-');
        plot(result.correlated.interval_mean', position*[1;1], 'k|');
        text(x_text, position+y_text_delta, 'Correlated case');

        % Revision specification: autocorrelation in the between-study
        % covariance rather than in the sampling-error covariance.
        fun5 = @(x)-phi_tau1(Y_i, X, V, x(1), x(2));
        x0 = [0.01, -0.1];
        [x_ML5, ~] = fmincon(fun5, x0, A, b, Aeq, beq, lb, ub);

        tau2_ML5 = x_ML5(1);
        rho_ML5 = x_ML5(2);
        M_ML5 = inv(X' * inv(Omega1(V,tau2_ML5,rho_ML5)) * X) * ...
                (X' * inv(Omega1(V,tau2_ML5,rho_ML5)) * Y_i);
        V_ML5_y = tau2_ML5 + trace(V)/k;
        st_err_ML5 = sqrt(V_ML5_y);
        V_ML5 = inv(X' * inv(Omega1(V,tau2_ML5,rho_ML5)) * X);
        st_err_M_ML5 = sqrt(V_ML5);

        result.alternative = struct( ...
            'M', M_ML5, ...
            'tau2', tau2_ML5, ...
            'rho', rho_ML5, ...
            'V_y', V_ML5_y, ...
            'V_mean', V_ML5, ...
            'interval_y', [M_ML5-my_q*st_err_ML5, ...
                           M_ML5+my_q*st_err_ML5], ...
            'interval_mean', [M_ML5-my_q*st_err_M_ML5, ...
                              M_ML5+my_q*st_err_M_ML5]);

        position = -3.5;
        plot(M_ML5, position, 'rd');
        plot(result.alternative.interval_y', position*[1;1], 'r-');
        plot(result.alternative.interval_mean', position*[1;1], 'k|');
        text(x_text+0.7, position+y_text_delta+0.1, '(a)');
        text(x_text+0.7, position+y_text_delta-0.4, '(b)');
    end

    result.figure_handle = figure_handle;

    %% Additional interval-progression figure for Section 4.2
    if my_case == 8.1
        [result.n_progression, result.additional_figure_handle] = ...
            plot_case_8_1_interval_progression(my_q, Y_i, sigma_i);
    end

    %% Optional, independently controlled PDF exports
    % Select the array position for this case's main figure. Position 4 is
    % reserved for the supplementary case-8.1 prediction-by-n figure.
    if my_case == 2
        print_main_figure = print_figures(1);
    elseif my_case == 8
        print_main_figure = print_figures(2);
    elseif my_case == 8.1
        print_main_figure = print_figures(3);
    else
        print_main_figure = print_figures(5);
    end

    if print_main_figure
        if my_case == 12
            output_name = sprintf( ...
                'Figure_meta_case_12_RT-H%d_Stage%d.pdf', ...
                data.metadata.hypothesis, data.metadata.stage);
        else
            output_name = sprintf('Figure_meta_case_%g_revision.pdf', my_case);
        end

        exportgraphics(figure_handle, ...
            fullfile(output_directory, output_name), ...
            'BackgroundColor', 'none', ...
            'ContentType', 'vector');
    end

    % The supplementary case-8.1 figure has its own indicator, so it can be
    % exported with or without the main case-8.1 forest plot.
    if my_case == 8.1 && print_figures(4)
        exportgraphics(result.additional_figure_handle, ...
            fullfile(output_directory, ...
                     'Figure_meta_case_8_1_prediction_interval_by_n.pdf'), ...
            'BackgroundColor', 'none', ...
            'ContentType', 'vector');
    end
end

%% Plot the Section 4.2 intervals as the number of inputs increases
function [progression, figure_handle] = ...
        plot_case_8_1_interval_progression(my_q, Y_i, sigma_i)
%PLOT_CASE_8_1_INTERVAL_PROGRESSION Plot equations (34)-(40) over n values.
%
% See Section 4.2 of the revised manuscript.
%
% For every n, the data-generating configuration is the one described in
% Section 4.2: n-1 inputs equal the first element of Y_i and one conflicting
% input equals its final element. The broad red region is the 95% prediction
% interval for a new input. The narrower blue region is the 95% confidence
% interval for beta and makes the distinction between equations (35) and
% (36) visible.

    n_values = (2:numel(Y_i))';
    concordant_estimate = Y_i(1);
    conflicting_estimate = Y_i(end);
    within_variance = sigma_i(1)^2;
    discrepancy = conflicting_estimate - concordant_estimate;

    % Equation (34): combined ML estimate with one conflicting input.
    beta_hat = concordant_estimate + discrepancy./n_values;

    % Equation (35): total variance used for prediction. The maximum
    % enforces the nonnegative constraint on the across-input variance.
    sigma2_total = max(within_variance*ones(size(n_values)), ...
        (n_values-1)./n_values.^2 * discrepancy^2);

    % Equation (36): variance of the combined estimator beta_hat.
    V_beta = max(within_variance./n_values, ...
        (n_values-1)./n_values.^3 * discrepancy^2);

    % Equation (40): 95% prediction interval for a new input.
    prediction_interval95 = [ ...
        beta_hat-my_q*sqrt(sigma2_total), ...
        beta_hat+my_q*sqrt(sigma2_total)];

    % Equation (39): 95% confidence interval for beta.
    confidence_interval95 = [ ...
        beta_hat-my_q*sqrt(V_beta), ...
        beta_hat+my_q*sqrt(V_beta)];

    % Return every plotted series so the numerical values can be inspected
    % or reused without reading them back from the graphics objects.
    progression = struct( ...
        'n', n_values, ...
        'beta_hat', beta_hat, ...
        'sigma2_total', sigma2_total, ...
        'V_beta', V_beta, ...
        'prediction_interval95', prediction_interval95, ...
        'confidence_interval95', confidence_interval95);

    % A fixed canvas avoids computer-dependent sizing. The wide aspect
    % ratio is suitable for insertion at the manuscript's text width.
    figure_handle = figure( ...
        'Units', 'pixels', ...
        'PaperPositionMode', 'auto', ...
        'Position', [100, 100, 560, 360], ...
        'PaperOrientation', 'landscape', ...
        'Name', 'Case 8.1: intervals as n increases', ...
        'NumberTitle', 'off');
    hold on;

    % Draw the broad prediction region first, then place the narrower
    % confidence region and the combined estimate on top of it.
    prediction_region = fill( ...
        [n_values; flipud(n_values)], ...
        [prediction_interval95(:,1); flipud(prediction_interval95(:,2))], ...
        [1.00, 0.90, 0.90], ...
        'EdgeColor', 'none');
    confidence_region = fill( ...
        [n_values; flipud(n_values)], ...
        [confidence_interval95(:,1); flipud(confidence_interval95(:,2))], ...
        [0.86, 0.91, 1.00], ...
        'EdgeColor', 'none');

    % Mark the two observation levels used throughout Section 4.2. Keep
    % these reference lines out of the legend so it describes only the
    % estimated intervals and their center.
    yline(concordant_estimate, ':', ...
        'Color', [0.35, 0.35, 0.35], ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
    yline(conflicting_estimate, ':', ...
        'Color', [0.35, 0.35, 0.35], ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');

    plot(n_values, prediction_interval95(:,1), 'r-', 'LineWidth', 1.0);
    plot(n_values, prediction_interval95(:,2), 'r-', 'LineWidth', 1.0);
    plot(n_values, confidence_interval95(:,1), 'b--', 'LineWidth', 1.0);
    plot(n_values, confidence_interval95(:,2), 'b--', 'LineWidth', 1.0);
    estimate_line = plot(n_values, beta_hat, 'kd-', ...
        'LineWidth', 1.0, ...
        'MarkerSize', 5, ...
        'MarkerFaceColor', 'w');

    xlabel('Number of inputs, n');
    ylabel('Estimate and 95% interval');
    xticks(n_values);
    xlim([2, 10]);
    ylim([floor(min(prediction_interval95(:,1)))-2, ...
          ceil(max(prediction_interval95(:,2)))+2]);
    box on;

    legend([prediction_region, confidence_region, estimate_line], ...
        {'95% prediction interval', '95% confidence interval', ...
         'Combined estimate'}, ...
        'Location', 'southeast');
end

%% Load and prepare one dataset
function data = load_case_data(my_case, my_q)
%LOAD_CASE_DATA Return a common data structure for the requested case.
%
% All branches populate Y_i, sigma_i, LB_i, title, and metadata. This
% normalizes the inputs before the common estimation code is called.

    metadata = struct();

    if my_case == 2
        % Doi et al. (2015-I), Figure 3, based on Collins et al. (1985).
        % The intervals are asymmetric on the original scale, so the point
        % estimates and bounds are converted to logs. As in the submitted
        % analysis, the standard errors are inferred from the lower bounds.
        Y_i =  [1.04 0.40 0.33 0.23 0.25 0.74 0.77 2.97 1.14]';
        LB_i = [0.48 0.20 0.14 0.08 0.13 0.59 0.39 0.59 0.69]';
        UB_i = [2.28 0.78 0.74 0.67 0.48 0.94 1.52 15.07 1.91]';

        Y_i = log(Y_i);
        LB_i = log(LB_i);
        UB_i = log(UB_i);
        sigma_i = (Y_i - LB_i) / my_q;

        metadata.UB_i = UB_i;
        metadata.dates = [1962 1962 1964 1964 1964 ...
                          1965 1966 1971 1975]';
        case_title = ['Example from Doi et al. (2015-I), Figure 3, ' ...
                      'based on Collins et al. (1985), in logs'];

    elseif my_case == 8
        % Original two-study conflicting-evidence example.
        Y_i = [72; 58];
        sigma_i = [1; 1];
        LB_i = Y_i - my_q*sigma_i;
        case_title = 'Two-study conflicting-evidence example';

    elseif my_case == 8.1
        % Section 4.2/referee example: nine mutually consistent inputs and
        % one conflicting input. All reported variances equal one, and the
        % conflicting input remains in the main analysis. The supplementary
        % figure derives both observation levels directly from this vector.
        Y_i = [72*ones(9, 1); 58];
        sigma_i = ones(10, 1);
        LB_i = Y_i - my_q*sigma_i;
        case_title = 'Section 4.2 ten-study conflicting-evidence example';

    elseif my_case == 12
        % Menkveld et al. (2024), Hypothesis H1, Stage 3.
        script_directory = fileparts(mfilename('fullpath'));
        input_file = fullfile(script_directory, 'RT_research_results.csv');
        assert(isfile(input_file), 'Input data file not found: %s', input_file);
        data_table = readtable(input_file);

        % Retain cross-hypothesis/stage quantiles for inspection.
        summary_stats_all = zeros(6*4, 7);
        summary_row = 0;
        for hypothesis_index = 1:6
            for stage_index = 1:4
                selection = ...
                    data_table.rt_hypothesis == hypothesis_index & ...
                    data_table.stage == stage_index;
                selected_table = data_table(selection, :);
                summary_row = summary_row + 1;
                summary_stats_all(summary_row, :) = quantile( ...
                    selected_table.estimate, ...
                    [0 0.10 0.25 0.50 0.75 0.90 1], ...
                    Method="approximate");
            end
        end

        hypothesis = 1;
        stage = 3;
        selection = data_table.rt_hypothesis == hypothesis & ...
                    data_table.stage == stage;
        data_table_filtered = data_table(selection, :);

        % Remove the top and bottom 5% of both estimates and reported
        % standard errors, reproducing the submitted filtering rule.
        Y_i_original = data_table_filtered.estimate;
        sigma_i_original = data_table_filtered.standard_error;
        remove_pct = 0.05;
        n_extreme = round(remove_pct*length(Y_i_original));

        [~, sorted_Y] = sort(Y_i_original);
        idx_smallest_Y = sorted_Y(1:n_extreme);
        idx_largest_Y = sorted_Y(end-n_extreme+1:end);

        [~, sorted_sigma] = sort(sigma_i_original);
        idx_smallest_sigma = sorted_sigma(1:n_extreme);
        idx_largest_sigma = sorted_sigma(end-n_extreme+1:end);

        remove_index = union(idx_smallest_Y, idx_largest_Y);
        remove_index = union(remove_index, idx_smallest_sigma);
        remove_index = union(remove_index, idx_largest_sigma);
        all_index = (1:length(Y_i_original))';
        my_points = setdiff(all_index, remove_index);

        Y_i = Y_i_original(my_points);
        sigma_i = sigma_i_original(my_points);
        LB_i = Y_i - my_q*sigma_i;

        metadata.hypothesis = hypothesis;
        metadata.stage = stage;
        metadata.my_points = my_points;
        metadata.k_case2 = height(data_table_filtered);
        metadata.Y_i_original = Y_i_original;
        metadata.summary_stats_all = summary_stats_all;
        case_title = sprintf( ...
            'Menkveld et al. (2024), RT-H%d, Stage %d', ...
            hypothesis, stage);

    else
        error('MetaAnalysis:UnsupportedCase', ...
              'Supported cases are 2, 8, 8.1, and 12.');
    end

    data = struct( ...
        'Y_i', Y_i, ...
        'sigma_i', sigma_i, ...
        'LB_i', LB_i, ...
        'title', case_title, ...
        'metadata', metadata);
end

%% Verify numerical results used in the revised manuscript
function verify_reference_results(case_results)
%VERIFY_REFERENCE_RESULTS Guard against accidental changes to key results.
%
% Targets reported to one and two decimal places use tolerances of 0.05 and
% 0.02, respectively. The NSE target uses 0.05 because percentile conventions
% can differ slightly across MATLAB releases. The corrected case-(a) targets
% use the AR(1) covariance consistently in both parts of the generalized
% least-squares estimator.

    doi = result_for_case(case_results, 2);
    conflict_two = result_for_case(case_results, 8);
    conflict_many = result_for_case(case_results, 8.1);
    menkveld = result_for_case(case_results, 12);

    one_decimal_tolerance = 0.05;
    manuscript_tolerance = 0.02;
    percentile_tolerance = 0.05;

    % Two conflicting inputs: confidence and prediction intervals.
    assert_close(conflict_two.CI_OLS, [55.3; 74.7], ...
        one_decimal_tolerance, 'case 8 confidence interval');
    assert_close(conflict_two.CI_RE, [51.3; 78.7], ...
        one_decimal_tolerance, 'case 8 prediction interval');

    % One conflicting input among n-1 concordant inputs, for n=2 and n=10.
    progression = conflict_many.n_progression;
    index_n2 = find(progression.n == 2, 1);
    index_n10 = find(progression.n == 10, 1);
    assert(~isempty(index_n2) && ~isempty(index_n10), ...
        'Case 8.1 progression must contain n=2 and n=10.');
    assert_close(progression.confidence_interval95(index_n2, :), ...
        [55.3, 74.7], one_decimal_tolerance, ...
        'case 8.1 n=2 confidence interval');
    assert_close(progression.prediction_interval95(index_n2, :), ...
        [51.3, 78.7], one_decimal_tolerance, ...
        'case 8.1 n=2 prediction interval');
    assert_close(progression.confidence_interval95(index_n10, :), ...
        [68.0, 73.2], one_decimal_tolerance, ...
        'case 8.1 n=10 confidence interval');
    assert_close(progression.prediction_interval95(index_n10, :), ...
        [62.4, 78.8], one_decimal_tolerance, ...
        'case 8.1 n=10 prediction interval');

    % Doi example: base, relative-precision, and correlated specifications.
    assert_close(doi.base.interval95_mean, [-0.92, -0.11], ...
        manuscript_tolerance, 'Doi base confidence interval');
    assert_close(doi.base.interval95_y, [-1.80, 0.77], ...
        manuscript_tolerance, 'Doi base prediction interval');
    assert_close(doi.relative.interval_mean, [-0.69, -0.09], ...
        manuscript_tolerance, 'Doi relative confidence interval');
    assert_close(doi.relative.interval_y, [-1.89, 1.11], ...
        manuscript_tolerance, 'Doi relative prediction interval');
    assert_close(doi.correlated.interval_mean, [-0.83, -0.05], ...
        manuscript_tolerance, 'Doi correlated (a) confidence interval');
    assert_close(doi.correlated.interval_y, [-1.51, 0.63], ...
        manuscript_tolerance, 'Doi correlated (a) prediction interval');
    assert_close(doi.alternative.interval_mean, [-1.05, 0.22], ...
        manuscript_tolerance, 'Doi correlated (b) confidence interval');
    assert_close(doi.alternative.interval_y, [-1.77, 0.94], ...
        manuscript_tolerance, 'Doi correlated (b) prediction interval');

    % Menkveld H1 Stage 3: input counts and plotted intervals.
    assert(menkveld.metadata.k_case2 == 164, ...
        'Case 12 must contain 164 unfiltered H1 Stage-3 observations.');
    assert(menkveld.k == 139, ...
        'Case 12 filtering must retain 139 H1 Stage-3 observations.');
    assert_close(menkveld.NSE.adjusted_interval95, [-7.27, 1.93], ...
        percentile_tolerance, 'case 12 adjusted NSE interval');
    assert_close(menkveld.base.interval95_y, [-9.06, 6.22], ...
        manuscript_tolerance, 'case 12 prediction interval');
end

function table1_results = collect_table1_results(case_results)
%COLLECT_TABLE1_RESULTS Assemble the four Doi-1 specifications in Table 1.
    doi = result_for_case(case_results, 2);
    reported_variance = mean(doi.sigma_i.^2);

    sigma_epsilon2 = [ ...
        doi.tau2_ML; ...
        doi.relative.tau2; ...
        doi.correlated.tau2; ...
        doi.alternative.tau2];
    sigma_zeta2 = [ ...
        reported_variance; ...
        doi.relative.sigma2_multiplier*reported_variance; ...
        reported_variance; ...
        reported_variance];
    sigma2 = sigma_epsilon2 + sigma_zeta2;

    case_name = ["Base"; "Relative"; "Correlated (a)"; "Correlated (b)"];
    sigma_epsilon_hat = sqrt(sigma_epsilon2);
    sigma_zeta = sqrt(sigma_zeta2);
    sigma_hat = sqrt(sigma2);
    variance_ratio = sigma_zeta2./sigma2;
    rho_hat = [NaN; NaN; doi.correlated.rho; doi.alternative.rho];

    table1_results = table(case_name, sigma_epsilon_hat, sigma_zeta, ...
        sigma_hat, variance_ratio, rho_hat, ...
        'VariableNames', {'Case', 'sigma_epsilon_hat', 'sigma_zeta', ...
                          'sigma_hat', 'variance_ratio', 'rho_hat'});
end

function print_table1_results(table1_results, number_of_inputs)
%PRINT_TABLE1_RESULTS Print manuscript Table 1 to three decimal places.
    fprintf('\nTable 1. Doi-1 estimation results (n=%d)\n', number_of_inputs);
    fprintf('%-17s %17s %12s %12s %15s %10s\n', ...
        'Case', 'sigma_epsilon', 'sigma_zeta', 'sigma', ...
        'variance ratio', 'rho');

    for row = 1:height(table1_results)
        if isnan(table1_results.rho_hat(row))
            rho_text = '';
        else
            rho_text = sprintf('%.3f', table1_results.rho_hat(row));
        end

        fprintf('%-17s %17.3f %12.3f %12.3f %15.3f %10s\n', ...
            char(table1_results.Case(row)), ...
            table1_results.sigma_epsilon_hat(row), ...
            table1_results.sigma_zeta(row), ...
            table1_results.sigma_hat(row), ...
            table1_results.variance_ratio(row), rho_text);
    end
end

function result = result_for_case(case_results, case_id)
%RESULT_FOR_CASE Return the unique result record for one case identifier.
    matches = find([case_results.case_id] == case_id);
    assert(numel(matches) == 1, ...
        'Expected exactly one result for case %g.', case_id);
    result = case_results(matches);
end

function assert_close(actual, expected, tolerance, description)
%ASSERT_CLOSE Check numerical agreement independent of row/column shape.
    actual = actual(:);
    expected = expected(:);
    assert(numel(actual) == numel(expected), ...
        '%s has an unexpected number of values.', description);

    maximum_difference = max(abs(actual-expected));
    assert(maximum_difference <= tolerance, ...
        '%s differs from its reference by %.4g (tolerance %.4g).', ...
        description, maximum_difference, tolerance);
end

%% Fixed figure layouts
function [position, x_text, y_text_delta, orientation] = ...
        figure_layout(my_case, LB_i)
%FIGURE_LAYOUT Return fixed dimensions calibrated to the submitted paper.
%
% Approximate submitted source sizes:
%   case 8:  272 x 149 points
%   case 2:  269 x 336 points
%   case 12: 404 x 501 points
%
% MATLAB figure positions are specified in pixels. The chosen dimensions
% reproduce those proportions under vector export while remaining large
% enough for labels to render consistently on macOS and Windows.

    if my_case == 8
        position = [100, 100, 447, 222];
        x_text = min(LB_i) - 5.1;
        y_text_delta = 0.25;
        orientation = 'landscape';
    elseif my_case == 8.1
        position = [100, 100, 447, 524];
        % Keep the labels inside the left axis while leaving enough room
        % before study 10's confidence interval.
        x_text = min(LB_i) - 2.5;
        y_text_delta = 0.25;
        orientation = 'landscape';
    elseif my_case == 2
        position = [100, 100, 447, 524];
        x_text = min(LB_i) - 0.3;
        y_text_delta = 0.4;
        orientation = 'landscape';
    else
        position = [100, 100, 668, 795];
        x_text = min(LB_i) - 0.3;
        y_text_delta = 0.4;
        orientation = 'portrait';
    end
end

%% Likelihood and covariance helpers
function residual = err(y, X, V, tau2)
%ERR Residuals for the base covariance model.
    beta_hat = inv(X' * inv(Omega(V,tau2)) * X) * ...
               (X' * inv(Omega(V,tau2)) * y);
    residual = y - X*beta_hat;
end

function residual = err1(y, X, V, tau2, rho)
%ERR1 Residuals for the alternative autocorrelation model.
    beta_hat = inv(X' * inv(Omega1(V,tau2,rho)) * X) * ...
               (X' * inv(Omega1(V,tau2,rho)) * y);
    residual = y - X*beta_hat;
end

function covariance = Omega(V, tau2)
%OMEGA Add independent between-study variance to sampling covariance.
    covariance = tau2*eye(size(V,1)) + V;
end

function covariance = Omega1(V, tau2, rho)
%OMEGA1 Apply AR(1)-style correlation to the between-study component.
    k = size(V,1);
    P_ac = eye(k);
    for j = 1:k-1
        P_ac = P_ac + rho^j * ...
               (diag(ones(k-j,1),j) + diag(ones(k-j,1),-j));
    end
    covariance = tau2*P_ac + V;
end

function likelihood = phi_tau(y, X, V, tau2)
%PHI_TAU Concentrated Gaussian log-likelihood kernel.
    residual = err(y, X, V, tau2);
    quadratic_form = residual' * inv(Omega(V,tau2)) * residual;
    likelihood = -(log(det(Omega(V,tau2))) + quadratic_form);
end

function likelihood = phi_tau1(y, X, V, tau2, rho)
%PHI_TAU1 Kernel for the alternative autocorrelation specification.
    residual = err1(y, X, V, tau2, rho);
    quadratic_form = residual' * inv(Omega1(V,tau2,rho)) * residual;
    likelihood = -(log(det(Omega1(V,tau2,rho))) + quadratic_form);
end

function covariance = V_ec(V, rho)
%V_EC Equicorrelated sampling covariance matrix.
    k = size(V,1);
    P = (ones(k,k)-eye(k))*rho + eye(k);
    root_V = sqrtm(V);
    covariance = root_V*P*root_V;
end

function covariance = V_ac(V, rho)
%V_AC AR(1)-style sampling covariance matrix.
    k = size(V,1);
    P_ac = eye(k);
    for j = 1:k-1
        P_ac = P_ac + rho^j * ...
               (diag(ones(k-j,1),j) + diag(ones(k-j,1),-j));
    end
    root_V = sqrtm(V);
    covariance = root_V*P_ac*root_V;
end
